In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r"ect.csv", engine='pyarrow')
df.head()

,provinceId,provinceName,divisionId,divisionNumber,districtId,districtName,subDistrictId,subDistrictName,unitId,unitNumber,unitName,displayUnitName
0,10,กรุงเทพมหานคร,1001,1,100101,พระนคร,10010101,พระบรมมหาราชวัง,1001010101,1,หอประชุม มหาวิทยาลัยศิลปากร ถนนมหาราช,1 - หอประชุม มหาวิทยาลัยศิลปากร ถนนมหาราช
1,10,กรุงเทพมหานคร,1001,1,100101,พระนคร,10010101,พระบรมมหาราชวัง,1001010102,2,โรงเรียนวัดมหาธาตุ ถนนพระจันทร์,2 - โรงเรียนวัดมหาธาตุ ถนนพระจันทร์
2,10,กรุงเทพมหานคร,1001,1,100101,พระนคร,10010101,พระบรมมหาราชวัง,1001010103,3,ศาลาหน้าอาคารวาสนะประทานวิทยาสิทธิ์ 1 โรงเรียน...,3 - ศาลาหน้าอาคารวาสนะประทานวิทยาสิทธิ์ 1 โรงเ...
3,10,กรุงเทพมหานคร,1001,1,100101,พระนคร,10010101,พระบรมมหาราชวัง,1001010104,4,โรงเรียนวัดพระเชตุพน ถนนมหาราช,4 - โรงเรียนวัดพระเชตุพน ถนนมหาราช
4,10,กรุงเทพมหานคร,1001,1,100101,พระนคร,10010102,วังบูรพาภิรมย์,1001010201,1,ตึกสามัคยาจารย์ โรงเรียนสวนกุหลาบวิทยาลัย ถนนต...,1 - ตึกสามัคยาจารย์ โรงเรียนสวนกุหลาบวิทยาลัย ...

In [7]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(df):
    # Remove leading and trailing whitespace in column: 'unitName'
    df['unitName'] = df['unitName'].str.strip()
    
    # to title case, cols
    # df.columns = df.columns.str.title()
    df.columns = map(lambda x: x[0].upper() + x[1:], df.columns)

    return df

df_clean = clean_data(df.copy())
df_clean.head()

,ProvinceId,ProvinceName,DivisionId,DivisionNumber,DistrictId,DistrictName,SubDistrictId,SubDistrictName,UnitId,UnitNumber,UnitName,DisplayUnitName
0,10,กรุงเทพมหานคร,1001,1,100101,พระนคร,10010101,พระบรมมหาราชวัง,1001010101,1,หอประชุม มหาวิทยาลัยศิลปากร ถนนมหาราช,1 - หอประชุม มหาวิทยาลัยศิลปากร ถนนมหาราช
1,10,กรุงเทพมหานคร,1001,1,100101,พระนคร,10010101,พระบรมมหาราชวัง,1001010102,2,โรงเรียนวัดมหาธาตุ ถนนพระจันทร์,2 - โรงเรียนวัดมหาธาตุ ถนนพระจันทร์
2,10,กรุงเทพมหานคร,1001,1,100101,พระนคร,10010101,พระบรมมหาราชวัง,1001010103,3,ศาลาหน้าอาคารวาสนะประทานวิทยาสิทธิ์ 1 โรงเรียน...,3 - ศาลาหน้าอาคารวาสนะประทานวิทยาสิทธิ์ 1 โรงเ...
3,10,กรุงเทพมหานคร,1001,1,100101,พระนคร,10010101,พระบรมมหาราชวัง,1001010104,4,โรงเรียนวัดพระเชตุพน ถนนมหาราช,4 - โรงเรียนวัดพระเชตุพน ถนนมหาราช
4,10,กรุงเทพมหานคร,1001,1,100101,พระนคร,10010102,วังบูรพาภิรมย์,1001010201,1,ตึกสามัคยาจารย์ โรงเรียนสวนกุหลาบวิทยาลัย ถนนต...,1 - ตึกสามัคยาจารย์ โรงเรียนสวนกุหลาบวิทยาลัย ...

In [8]:
df_clean.to_parquet("ect.parquet", index=False)